### ISSUE TITLE
3.3V?

### ISSUE THREAD

**Issue by KennanHunter** [3DBuffalo/MAGsense#1]
Your data sheet mentions that the component operates at 3.3V. There's no output on a standard FTC/FRC robot at that level, which makes it a little strange of a component. Perhaps you meant to specify the same voltage range as the [DRV5032FBDBZR](https://www.digikey.com/en/products/detail/texas-instruments/DRV5032FBDBZR/7173718) you use, which would put it at 1.65V ~ 5.5V, able to be powered by the 5V output of the FRC VRM.

**Comment by 3DBuffalo** [comment]
Thank you for bringing this to our attention. You are correct that the component can operate beyond 3.3V, and we sincerely apologize for the improper wording in our datasheet. We have since updated the datasheet to reflect the correct operating voltage range of 1.65V ~ 5.5V, consistent with components like the DRV5032FBDBZR.

We can confirm from our testing that the sensor operates reliably at both 3.3V and 5V, aligning with the standard outputs of FTC/FRC robotics systems. Specifically:

The [REV Control Hub](https://docs.revrobotics.com/duo-control/control-system-overview/control-hub-basics) supplies 3.3V to its digital ports, ensuring compatibility.
The roboRIO supplies 5V, which also falls within the operational range of the sensor.
We appreciate your diligence and feedback, as it helps us provide clearer and more accurate information. Please don't hesitate to reach out if you have any further questions or require additional support.

**Comment by KennanHunter** [comment]
Forgot expansion hubs gave 3.3 on digital, thanks for updating so quickly though!
